# Changes here will be overwritten by Copier
_commit: 3b67e70
_src_path: git@github.com:luca-penasa/wolt-python-package-cookiecutter.git
author_email: luca.penasa@inaf.it
author_name: Luca Penasa
github_username: JANUS-JUICE
module_name: janus_ssmm_tlm_info
project_name: JANUS SSMM Telemetry Info
project_short_desription: Provides reusable functions to inspect Janus scientific
    telemetry within ssmm files.
project_url_slug: janus-ssmm-tlm-info
publish_docs_on_gh_pages: false
publish_package_on_pypi: false
